return {
    {
        key = "card_flight_trail",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:card_flight_trail",
        source_assets = {
            "assets/ui/promoted/icons/leaf.png",
            "assets/ui/promoted/icons/seed.png",
            "assets/ui/promoted/icons/clean_spark.png",
        },
        runtime_path = "assets/ui/effects/card_flight_trail.png",
        frame_w = 32,
        frame_h = 16,
        frames = 6,
        fps = 18,
        pivot_x = 16,
        pivot_y = 8,
        anchor = "card_center",
        blend = "alpha",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab", "garden-stacks-number" },
    },
    {
        key = "pile_landing_puff",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_landing_puff",
        source_assets = {
            "assets/ui/promoted/icons/leaf.png",
            "assets/ui/promoted/icons/flower.png",
            "assets/ui/promoted/icons/seed.png",
        },
        runtime_path = "assets/ui/effects/pile_landing_puff.png",
        frame_w = 32,
        frame_h = 32,
        frames = 6,
        fps = 18,
        pivot_x = 16,
        pivot_y = 20,
        anchor = "pile_top",
        blend = "alpha",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab", "garden-stacks-number" },
    },
    {
        key = "combo_gold_burst",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:combo_gold_burst",
        source_assets = {
            "assets/ui/promoted/icons/star.png",
            "assets/ui/promoted/icons/clean_spark.png",
            "assets/ui/promoted/icons/coin.png",
        },
        runtime_path = "assets/ui/effects/combo_gold_burst.png",
        frame_w = 48,
        frame_h = 48,
        frames = 8,
        fps = 20,
        pivot_x = 24,
        pivot_y = 24,
        anchor = "pile_top",
        blend = "add",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab", "garden-stacks-number" },
    },
    {
        key = "combo_break_shard",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:combo_break_shard",
        source_assets = {
            "assets/ui/promoted/icons/warning.png",
            "assets/ui/promoted/icons/leaf.png",
            "assets/ui/promoted/icons/seed.png",
        },
        runtime_path = "assets/ui/effects/combo_break_shard.png",
        frame_w = 40,
        frame_h = 32,
        frames = 6,
        fps = 18,
        pivot_x = 20,
        pivot_y = 16,
        anchor = "pile_top",
        blend = "alpha",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab" },
    },
    {
        key = "discovery_stamp",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:discovery_stamp",
        source_assets = {
            "assets/generated/garden_stacks/discovery/stamp_combo_discovery.png",
        },
        runtime_path = "assets/ui/effects/discovery_stamp.png",
        frame_w = 64,
        frame_h = 40,
        frames = 4,
        fps = 12,
        pivot_x = 32,
        pivot_y = 20,
        anchor = "reward_card",
        blend = "alpha",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab" },
    },
    {
        key = "coin_sparkle",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:coin_sparkle",
        source_assets = {
            "assets/ui/promoted/icons/coin.png",
            "assets/ui/promoted/icons/clean_spark.png",
        },
        runtime_path = "assets/ui/effects/coin_sparkle.png",
        frame_w = 32,
        frame_h = 32,
        frames = 6,
        fps = 18,
        pivot_x = 16,
        pivot_y = 16,
        anchor = "coin_counter",
        blend = "add",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab" },
    },
    {
        key = "reward_halo",
        role = "effect_sprite",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:reward_halo",
        source_assets = {
            "assets/ui/promoted/icons/leaf.png",
            "assets/ui/promoted/icons/clean_spark.png",
            "assets/ui/promoted/icons/star.png",
        },
        runtime_path = "assets/ui/effects/reward_halo.png",
        frame_w = 64,
        frame_h = 64,
        frames = 4,
        fps = 8,
        pivot_x = 32,
        pivot_y = 32,
        anchor = "reward_card",
        blend = "alpha",
        scale_policy = "fixed_2x",
        allowed_scenes = { "garden-stacks-ui-lab" },
    },
    {
        key = "pile_focus_corners",
        role = "fixed_ui_glyph",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_focus_corners",
        source_assets = {
            "assets/ui/promoted/garden_templates/60_item_slot_square.png",
        },
        runtime_path = "assets/ui/effects/pile_focus_corners.png",
        frame_w = 112,
        frame_h = 112,
        frames = 1,
        fps = 1,
        pivot_x = 56,
        pivot_y = 56,
        anchor = "pile_rect",
        blend = "alpha",
        scale_policy = "fixed_integer",
        allowed_scenes = { "garden-stacks-number" },
    },
}
