return {
    {
        key = "meadow",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/meadow.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:motif_meadow",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_meadow.png",
            "assets/ui/promoted/icons/flower.png",
        },
        w = 88,
        h = 88,
        scale_policy = "fixed_integer",
    },
    {
        key = "forest",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/forest.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:motif_forest",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_forest.png",
            "assets/ui/promoted/icons/tree.png",
        },
        w = 88,
        h = 88,
        scale_policy = "fixed_integer",
    },
    {
        key = "dune",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/dune.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:motif_dune",
        source_assets = {
            "assets/generated/garden_stacks/cards/work_soil_test.png",
            "assets/ui/promoted/icons/sun.png",
        },
        w = 88,
        h = 88,
        scale_policy = "fixed_integer",
    },
    {
        key = "wetland",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/wetland.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:motif_wetland",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_wetland.png",
            "assets/ui/promoted/icons/water_drop.png",
        },
        w = 88,
        h = 88,
        scale_policy = "fixed_integer",
    },
    {
        key = "pile_patch_meadow",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/pile_patch_meadow.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_patch_meadow",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_meadow.png",
            "assets/ui/promoted/icons/flower.png",
            "assets/ui/promoted/icons/leaf.png",
        },
        w = 112,
        h = 72,
        scale_policy = "fixed_integer",
    },
    {
        key = "pile_patch_forest",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/pile_patch_forest.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_patch_forest",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_forest.png",
            "assets/ui/promoted/icons/tree.png",
            "assets/ui/promoted/icons/leaf.png",
        },
        w = 112,
        h = 72,
        scale_policy = "fixed_integer",
    },
    {
        key = "pile_patch_dune",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/pile_patch_dune.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_patch_dune",
        source_assets = {
            "assets/generated/garden_stacks/cards/work_soil_test.png",
            "assets/ui/promoted/icons/sun.png",
            "assets/ui/promoted/icons/seed.png",
        },
        w = 112,
        h = 72,
        scale_policy = "fixed_integer",
    },
    {
        key = "pile_patch_wetland",
        role = "object_bitmap",
        runtime_path = "assets/ui/pile_motifs/pile_patch_wetland.png",
        source_path = "prototype/emoji_garden/scripts/build_garden_stacks_ui_polish_assets.py:pile_patch_wetland",
        source_assets = {
            "assets/generated/garden_stacks/cards/floor_wetland.png",
            "assets/ui/promoted/icons/water_drop.png",
            "assets/ui/promoted/icons/reeds.png",
        },
        w = 112,
        h = 72,
        scale_policy = "fixed_integer",
    },
}
