import fs from "node:fs";
import path from "node:path";

const root = path.resolve(new URL("..", import.meta.url).pathname);
const legacyInputs = [
  "src/performance.js",
  "src/game/random.js",
  "src/game/catalog.js",
  "src/game/number-solitaire.js",
  "src/game/run-mode.js",
  "src/game/storage.js",
];
const builds = [
  { name: "legacy", inputs: [...legacyInputs, "src/app.js"], output: "public/app.bundle.js" },
  {
    name: "hourly",
    inputs: [
      "src/performance.js",
      "src/game/random.js",
      "src/game/hourly-harvest.js",
      "src/ui/pointer-drag.js",
      "src/simple-app.js",
    ],
    output: "simple/simple.bundle.js",
  },
];

function requestedTarget(argv) {
  const inline = argv.find((value) => value.startsWith("--target="));
  if (inline) return inline.slice("--target=".length);
  const index = argv.indexOf("--target");
  return index >= 0 ? argv[index + 1] : "";
}

const target = requestedTarget(process.argv.slice(2));
const selectedBuilds = target ? builds.filter((build) => build.name === target) : builds;
if (target && selectedBuilds.length === 0) {
  throw new Error(`Unknown build target: ${target}. Use hourly or legacy.`);
}

function stripImports(source) {
  let out = "";
  let index = 0;
  while (index < source.length) {
    const next = source.indexOf("import", index);
    if (next < 0) {
      out += source.slice(index);
      break;
    }
    const before = source.slice(index, next);
    if (!/^\s*$/.test(before.split("\n").pop())) {
      out += source.slice(index, next + 6);
      index = next + 6;
      continue;
    }
    out += before;
    const end = source.indexOf(";", next);
    if (end < 0) break;
    index = end + 1;
  }
  return out;
}

function toScript(source) {
  return stripImports(source)
    .replace(/^export\s+const\s+/gm, "const ")
    .replace(/^export\s+function\s+/gm, "function ")
    .replace(/^export\s+\{\s*[^}]+\s*\};?\s*$/gm, "")
    .replace(/^export\s+default\s+/gm, "");
}

const banner = `// Generated by scripts/build-offline.mjs. Edit src/ files instead.\n`;

for (const build of selectedBuilds) {
  const body = build.inputs
    .map((file) => {
      const source = fs.readFileSync(path.join(root, file), "utf8");
      return `\n// ---- ${file} ----\n${toScript(source)}\n`;
    })
    .join("\n");
  const outputPath = path.join(root, build.output);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${banner}(() => {\n"use strict";\n${body}\n})();\n`);
  console.log(`wrote ${build.output} (${build.name})`);
}
